APF-976: Use commons-dbcp 1.2.2 with Tapestry since there's a NoSuchMethodError if 1.2.1 is used.
git-svn-id: https://appfuse.dev.java.net/svn/appfuse/trunk@3128 2aeb74e6-0f1c-0410-991c-92d95bb9df37