Reverted to Spring Modules 0.5 since the 0.6 version has dependencies on Hibernate 3.2.0 RC candidates which cause NoClassDefFoundErrors
git-svn-id: https://appfuse.dev.java.net/svn/appfuse/trunk@2271 2aeb74e6-0f1c-0410-991c-92d95bb9df37