APF-825: Reverted upgrade to Commons FileUpload 1.2 (not compatible with Spring 2.0.6's CommonsMultipartResolve). Error thrown is:
[INFO] [talledLocalContainer] SEVERE: Servlet.service() for servlet default threw exception
[INFO] [talledLocalContainer] java.lang.NoClassDefFoundError: org/apache/commons/io/output/DeferredFileOutputStream

git-svn-id: https://appfuse.dev.java.net/svn/appfuse/trunk@2808 2aeb74e6-0f1c-0410-991c-92d95bb9df37